In [1]:
import os
import glob
import pandas as pd

file_list = glob.glob('Country/*.xlsx')

df_list = []
for file in file_list:
    df = pd.read_excel(file)

    df['country'] = os.path.splitext(os.path.basename(file))[0]

    df_list.append(df)

df_combined = pd.concat(df_list, ignore_index=True)

df_combined.head()

,TradeStat->Eidb->Import->Country-wise-all-commodities,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,country
0,Report Generated on: 8/10/2026 - Values in US ...,NaN,NaN,NaN,NaN,NaN,angola
1,S.No.,HSCode,Commodity,2024-2025,2025-2026,%Growth,angola
2,1,0106,OTHER LIVE ANIMALS,0,0,NaN,angola
3,2,2506,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,0.03,0.03,2.39,angola
4,3,2515,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",0,0.01,NaN,angola

In [2]:
df_combined = df_combined.iloc[1:]
df_combined.head()

,TradeStat->Eidb->Import->Country-wise-all-commodities,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,country
1,S.No.,HSCode,Commodity,2024-2025,2025-2026,%Growth,angola
2,1,0106,OTHER LIVE ANIMALS,0,0,NaN,angola
3,2,2506,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,0.03,0.03,2.39,angola
4,3,2515,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",0,0.01,NaN,angola
5,4,2516,GRANITE PROPHYRY ETC AND OTHR MONUMENTAL/ BL...,0.81,0.82,0.68,angola

In [3]:
df_combined.columns = df_combined.iloc[0]

df_combined = df_combined[1:]

df_combined.head()

1,S.No.,HSCode,Commodity,2024-2025,2025-2026,%Growth,angola
2,1,0106,OTHER LIVE ANIMALS,0,0,NaN,angola
3,2,2506,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,0.03,0.03,2.39,angola
4,3,2515,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",0,0.01,NaN,angola
5,4,2516,GRANITE PROPHYRY ETC AND OTHR MONUMENTAL/ BL...,0.81,0.82,0.68,angola
6,5,2601,"IRON ORES AND CONCENTRATES, INCLUDING ROAS...",0,0,NaN,angola

In [4]:
df_combined = df_combined.drop(columns=['2024-2025', '%Growth', 'Commodity', 'S.No.'])

In [5]:
df_combined = df_combined.rename(columns={'angola': 'country', 'HSCode': 'hs4_code', '2025-2026': 'import_sales'})

In [6]:
df_combined.head()

1 hs4_code import_sales country
2     0106            0  angola
3     2506         0.03  angola
4     2515         0.01  angola
5     2516         0.82  angola
6     2601            0  angola

In [7]:
df_combined['hs4_code'] = df_combined['hs4_code'].astype(str)

df_combined['hs2_code'] = df_combined['hs4_code'].str[:2]
df_combined.head()

1 hs4_code import_sales country hs2_code
2     0106            0  angola       01
3     2506         0.03  angola       25
4     2515         0.01  angola       25
5     2516         0.82  angola       25
6     2601            0  angola       26

In [8]:
df_commodity = pd.read_excel('dim_commodity.xlsx')
df_commodity.head()

,commodity_key,hs2_code,hs4_code,commodity,description,2025_2026_import_sales_usd
0,1,1,101,LIVE ANIMALS.,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35
1,2,1,102,LIVE ANIMALS.,LIVE BOVINE ANIMALS,1.30
2,3,1,103,LIVE ANIMALS.,LIVE SWINE,0.40
3,4,1,104,LIVE ANIMALS.,LIVE SHEEP AND GOATS,2.65
4,5,1,105,LIVE ANIMALS.,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15

In [9]:
df_combined['hs4_code'] = df_combined['hs4_code'].astype(str).str.strip()
df_commodity['hs4_code'] = df_commodity['hs4_code'].astype(str).str.strip().str.zfill(4)

merged_df = pd.merge(df_combined, df_commodity, on='hs4_code')
merged_df.head()

,hs4_code,import_sales,country,hs2_code_x,commodity_key,hs2_code_y,commodity,description,2025_2026_import_sales_usd
0,0106,0,angola,01,6,1,LIVE ANIMALS.,OTHER LIVE ANIMALS,8.67
1,2506,0.03,angola,25,192,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,13.39
2,2515,0.01,angola,25,201,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",353.06
3,2516,0.82,angola,25,202,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,GRANITE PROPHYRY ETC AND OTHR MONUMENTAL/ BL...,12.20
4,2601,0,angola,26,216,26,"ORES, SLAG AND ASH.","IRON ORES AND CONCENTRATES, INCLUDING ROAS...",1254.22

In [10]:
merged_df.head(40)

,hs4_code,import_sales,country,hs2_code_x,commodity_key,hs2_code_y,commodity,description,2025_2026_import_sales_usd
0,0106,0,angola,01,6,1,LIVE ANIMALS.,OTHER LIVE ANIMALS,8.67
1,2506,0.03,angola,25,192,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,13.39
2,2515,0.01,angola,25,201,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",353.06
3,2516,0.82,angola,25,202,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,GRANITE PROPHYRY ETC AND OTHR MONUMENTAL/ BL...,12.20
4,2601,0,angola,26,216,26,"ORES, SLAG AND ASH.","IRON ORES AND CONCENTRATES, INCLUDING ROAS...",1254.22
5,2709,3586.39,angola,27,244,27,"MINERAL FUELS, MINERAL OILS AND PRODUCTS OF TH...",PETROLEUM OILS AND OILS OBTAINED FROM BITU...,134716.78
6,2710,0,angola,27,245,27,"MINERAL FUELS, MINERAL OILS AND PRODUCTS OF TH...",PETROLEUM OILSAND OILS OBTND FRM BITMNS MN...,9319.64
7,2711,1274.56,angola,27,246,27,"MINERAL FUELS, MINERAL OILS AND PRODUCTS OF TH...",PETRLM GASES AND OTHR GASEOUS HYDRCRBNS,26633.66
8,2804,0,angola,28,255,28,INORGANIC CHEMICALS; ORGANIC OR INORGANIC COMP...,"HYDROGEN, RARE GASES AND OTHER NON-METALS",473.89
9,2941,0,angola,29,340,29,ORGANIC CHEMICALS,ANTIBIOTICS,1866.32
10,3802,0,angola,38,403,38,MISCELLANEOUS CHEMICAL PRODUCTS.,ACTVTD CRBN-ACTVTD NATRL MNRL PRODCTS-ANMLBLAC...,103.83
11,3914,0,angola,39,442,39,PLASTIC AND ARTICLES THEREOF.,ION EXCHANGERS BASED ON POLYMERS OF HEAD...,74.32
12,4203,0,angola,42,485,42,"ARTICLES OF LEATHER,SADDLERY AND HARNESS;TRAVE...",ARTICLES OF APPAREL AND CLOTHING ACCE...,18.31
13,4819,0,angola,48,542,48,"PAPER AND PAPERBOARD; ARTICLES OF PAPER PULP, ...","CARTONS, BOXES, CASES, BAGS AND OTHER PACK...",106.56
14,5407,0,angola,54,605,54,MAN-MADE FILAMENTS.,WOVN FBRCS OF SYNTHTC FILAMENT YARN INCL WOVN...,408.66
15,6110,0,angola,61,674,61,"ARTICLES OF APPAREL AND CLOTHING ACCESSORIES, ...","JERSEYS, PULLOVERS, CARDIGANS, WAISTCOATS AND ...",148.36
16,6310,0.01,angola,63,708,63,OTHER MADE UP TEXTILE ARTICLES; SETS; WORN CLO...,"USD/NEW RAGS,SCRP TWNE,CORDGE,ROPE AND CB...",271.33
17,7010,0,angola,70,765,70,GLASS AND GLASSWARE.,"CARBOYS,BOTLS,FLSKS,JARS ETC FOR CNVYANCE OR P...",138.57
18,7102,0.24,angola,71,776,71,"NATURAL OR CULTURED PEARLS,PRECIOUS OR SEMIPRE...","DIAMONDS, WHETHER OR NOT WORKED, BUT NOT MOUN...",16408.69
19,7204,0,angola,72,796,72,IRON AND STEEL,FERROUS WASTE AND SCRAP; REMELTING SCRAP INGOTS,4558.72
20,7311,0.04,angola,73,832,73,ARTICLES OF IRON OR STEEL,"CONTAINERS FOR COMPRESSED OR LIQUEFIED GAS,...",76.67
21,7318,0,angola,73,839,73,ARTICLES OF IRON OR STEEL,"SCRWES,BOLTS,NUTS,COACHSCREWS,SCREW HOOKS RIVE...",1150.93
22,7503,0,angola,75,866,75,NICKEL AND ARTICLES THEREOF.,NICKEL WASTE AND SCRAP,47.74
23,7601,0,angola,76,872,76,ALUMINIUM AND ARTICLES THEREOF.,UNWROUGHT ALUMINIUM,1334.73
24,7602,0.27,angola,76,873,76,ALUMINIUM AND ARTICLES THEREOF.,ALUMINIUM WASTE AND SCRAP,4550.58
25,7801,0.2,angola,78,888,78,LEAD AND ARTICLES THEREOF.,UNWROUGHT LEAD,747.14
26,8406,0,angola,84,945,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",STEAM TURBINES AND OTHER VAPOUR TURBINES,127.77
27,8410,0,angola,84,949,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...","HYDRAULIC TURBINES, WATER WHEELS, ANDR...",6.15
28,8412,0,angola,84,951,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",OTHER ENGINES AND MOTORS,735.98
29,8421,0,angola,84,960,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...","CENTRIFUGES, INCLUDING CENTRIFUGAL DRYERS; FIL...",1872.36
30,8431,0.15,angola,84,970,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",PRTS SUITBL FR USE SOLELY/PRNCPLY WTH THE MCHN...,1973.92
31,8442,0,angola,84,981,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...","MCHNRY,APPRTS AND EQPMNT(EXCL OF 8456 TO...",83.38
32,8455,0,angola,84,994,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",METAL-ROLLING MILLS AND ROLLS THEREFOR,940.99
33,8479,0.01,angola,84,1017,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",MCHNS AND MCHNCL APPLNCS HVNG INDVDL FU...,4131.45
34,8480,0,angola,84,1018,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",MOULDING BOXES FOR METAL FOUNDRY; MOULD BASE...,1137.27
35,8481,0.01,angola,84,1019,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...","TAPS, COCKS, VALVES AND SIMILAR APPLIANCES FOR...",2423.30
36,8482,0.02,angola,84,1020,84,"NUCLEAR REACTORS, BOILERS, MACHINERY AND MECHA...",BALL OR ROLLER BEARINGS,1568.34
37,8504,0.02,angola,85,1029,85,ELECTRICAL MACHINERY AND EQUIPMENT AND PARTS T...,"ELECTRICAL TRANSFORMERS, STATIC CONVERTERS (FO...",4404.92
38,8517,0,angola,85,1042,85,ELECTRICAL MACHINERY AND EQUIPMENT AND PARTS T...,"ELCTRCL APARTS FR LINE TELEPHNY/TELGRPHY, INCL...",21715.58
39,8528,0.01,angola,85,1052,85,ELECTRICAL MACHINERY AND EQUIPMENT AND PARTS T...,"RECEPTION APARATUS,WH/NOT INCORPRTNG RADIOBROD...",1098.04

In [11]:
merged_df.loc[merged_df['country'] == 'usa', 'country'] = 'U S A'
merged_df.loc[merged_df['country'] == 'china', 'country'] = 'CHINA P RP'
merged_df.loc[merged_df['country'] == 'uae', 'country'] = 'U ARAB EMTS'
merged_df.loc[merged_df['country'] == 'uk', 'country'] = 'U K'

merged_df['country'] = merged_df['country'].str.upper()

In [12]:
df_country = pd.read_excel('dim_country.xlsx')
df_country.head()

,country_key,country,region,continent,import_sales_usd_country_2025_2026
0,1,AFGHANISTAN,South Asia,Asia,654.22
1,2,ALBANIA,Other European Countries,Europe,4.78
2,3,ALGERIA,North Africa,Africa,358.65
3,4,AMERI SAMOA,Unspecified Region,Unspecified Region,0.01
4,5,ANDORRA,Unspecified Region,Unspecified Region,0.25

In [13]:
final_df = pd.merge(merged_df, df_country, on='country')
final_df.head()

,hs4_code,import_sales,country,hs2_code_x,commodity_key,hs2_code_y,commodity,description,2025_2026_import_sales_usd,country_key,region,continent,import_sales_usd_country_2025_2026
0,0106,0,ANGOLA,01,6,1,LIVE ANIMALS.,OTHER LIVE ANIMALS,8.67,6,Other South African Countries,Africa,4862.8
1,2506,0.03,ANGOLA,25,192,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,QRTZ (OTHR THN NATRL SANDS) QRTZTE W/N ROUG...,13.39,6,Other South African Countries,Africa,4862.8
2,2515,0.01,ANGOLA,25,201,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,"MARBLE, TRAVERTINE, ECAUSSINE AND OTHER CALC...",353.06,6,Other South African Countries,Africa,4862.8
3,2516,0.82,ANGOLA,25,202,25,SALT; SULPHUR; EARTHS AND STONE; PLASTERING MA...,GRANITE PROPHYRY ETC AND OTHR MONUMENTAL/ BL...,12.20,6,Other South African Countries,Africa,4862.8
4,2601,0,ANGOLA,26,216,26,"ORES, SLAG AND ASH.","IRON ORES AND CONCENTRATES, INCLUDING ROAS...",1254.22,6,Other South African Countries,Africa,4862.8

In [14]:
final_df = final_df[final_df['import_sales'] != 0]

In [15]:
final_df = final_df.drop(columns=['hs4_code', 'country', 'hs2_code_x', 'hs2_code_y', 'commodity', 'description', '2025_2026_import_sales_usd', 'region', 'continent', 'import_sales_usd_country_2025_2026'])

In [16]:
final_df.to_excel('fact_imports.xlsx', index=False)